(autoload 'adoc-re-attribute-entry              "adoc-mode" "" nil)
(autoload 'adoc-re-one-line-title               "adoc-mode" "" nil)
(autoload 'adoc-make-one-line-title             "adoc-mode" "" nil)
(autoload 'adoc-re-two-line-title               "adoc-mode" "" nil)
(autoload 'adoc-make-two-line-title             "adoc-mode" "" nil)
(autoload 'adoc-re-oulisti                      "adoc-mode" "" nil)
(autoload 'adoc-make-uolisti                    "adoc-mode" "" nil)
(autoload 'adoc-re-llisti                       "adoc-mode" "" nil)
(autoload 'adoc-re-delimited-block-line         "adoc-mode" "" nil)
(autoload 'adoc-re-delimited-block              "adoc-mode" "" nil)
(autoload 'adoc-re-verbatim-paragraph-sequence  "adoc-mode" "" nil)
(autoload 'adoc-re-precond                      "adoc-mode" "" nil)
(autoload 'adoc-re-quote-precondition           "adoc-mode" "" nil)
(autoload 'adoc-re-unconstrained-quote          "adoc-mode" "" nil)
(autoload 'adoc-re-constrained-quote            "adoc-mode" "" nil)
(autoload 'adoc-re-quote                        "adoc-mode" "" nil)
(autoload 'adoc-re-paragraph-separate           "adoc-mode" "" nil)
(autoload 'adoc-re-paragraph-start              "adoc-mode" "" nil)
(autoload 'adoc-re-aor                          "adoc-mode" "" nil)
(autoload 'adoc-re-ror                          "adoc-mode" "" nil)
(autoload 'adoc-re-cell-specifier               "adoc-mode" "" nil)
(autoload 'adoc-facespec-subscript              "adoc-mode" "" nil)
(autoload 'adoc-facespec-superscript            "adoc-mode" "" nil)
(autoload 'adoc-lexxer                          "adoc-mode" "" nil)
(autoload 'adoc-kw-one-line-title               "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-two-line-title               "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-oulisti                      "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-llisti                       "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-delimited-block              "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-delimtier-line-fallback      "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-admonition-paragraph         "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-verbatim-paragraph-sequence  "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-quote                        "adoc-mode" "" nil 'macro)
(autoload 'adoc-kw-replacement                  "adoc-mode" "" nil 'macro)
(autoload 'adoc-unfontify-region-function       "adoc-mode" "" nil)
(autoload 'adoc-font-lock-mark-block-function   "adoc-mode" "" nil)
(autoload 'adoc-get-font-lock-keywords          "adoc-mode" "" nil)
(autoload 'adoc-show-version                    "adoc-mode" "" t)
(autoload 'adoc-goto-ref-label                  "adoc-mode" "" t)
(autoload 'adoc-title-descriptor                "adoc-mode" "" nil)
(autoload 'adoc-make-title                      "adoc-mode" "" nil)
(autoload 'adoc-modify-title                    "adoc-mode" "" nil)
(autoload 'adoc-promote-title                   "adoc-mode" "" t)
(autoload 'adoc-denote-title                    "adoc-mode" "" t)
(autoload 'adoc-adjust-title-del                "adoc-mode" "" t)
(autoload 'adoc-toggle-title-type               "adoc-mode" "" t)
(autoload 'adoc-make-unichar-alist              "adoc-mode" "" nil)
(autoload 'adoc-unichar-by-name                 "adoc-mode" "" nil)
(autoload 'adoc-entity-to-string                "adoc-mode" "" nil)
(autoload 'adoc-calc                            "adoc-mode" "" t)
(autoload 'adoc-mode                            "adoc-mode" "" t)
(provide 'adoc-mode-epackage-autoloads)
